name: publish-paging-efcore

on:
  push:
    tags:
      - '^paging-v\d\.\d\.\d'

jobs:
  build-publish:
    name: pubilsh Paging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.1
      - name: Build-Pack
        run: cd src/La.AspNetCore.Extensions.Paging & \
             dotnet pack -c Release
      - name: Pubilsh to baget
        run: cd src/La.AspNetCore.Extensions.Paging/bin/Release & \
            dotnet nuget push -s https://baget.laggage.top/v3/index.json .\ -k ${{BAGET_KEY}}
